server:
  port: 8080

spring:
  lifecycle:
    timeout-per-shutdown-phase: 1m

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: validate # create, update, validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
        hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    show-sql: false
    generate-ddl: true
    open-in-view: false

  datasource:
    url: jdbc:mysql://localhost:3306/collect?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password:
    hikari:
      max-lifetime: 60000
      connection-timeout: 60000
      validation-timeout: 10000

client:
  host:

logging:
  level:
    root: info

server:
  shutdown: immediate # default
